/**
 * The PIPELINE parser: the traced LALR(1) machine generated by our own table
 * constructor (grammar/lalr.ts) from the C-subset grammar. This is the parse
 * the rest of the compiler consumes (docs/PLAN.md "pipeline honesty").
 *
 * The table is built once and memoized. The only conflicts the grammar is
 * allowed to have are dangling-else shift/reduce conflicts, resolved by shift
 * with the §4.8.2 explanation; anything else throws (and the syntax-lr tests
 * assert it).
 */
import type { Recorded } from '@lab/trace';
import { type Diagnostic, type SourceSpan } from '../common/types.js';
import type { TokenStream } from '../csubset/tokens.js';
import { cGrammar } from '../csubset/grammar-def.js';
import type { Grammar } from '../grammar/grammar.js';
import { drain, type LrConflictJson } from '../grammar/lr-events.js';
import { lalrSteps, type LalrResult } from '../grammar/lalr.js';
import {
  lrParseRun,
  type LrParseEvent,
  type LrParseResult,
  type LrParseUiState,
  type ParseInputSym,
} from '../grammar/lr-parse.js';
import type { Ast } from './types.js';
import { buildAst } from './build.js';

export interface PipelineTables {
  grammar: Grammar;
  /** Full LALR construction result: merged states, transitions, ACTION/GOTO,
   *  and the (resolved) dangling-else conflicts. */
  lalr: LalrResult;
  /** The recorded shift-by-default resolutions (all dangling-else). */
  resolutions: LrConflictJson[];
}

let cachedTables: PipelineTables | null = null;

/**
 * Build (once) the LALR(1) table for cGrammar(). Shift/reduce conflicts on
 * 'else' matching the dangling-else shape are resolved by SHIFT (§4.8.2);
 * any other conflict means the grammar drifted out of LALR(1) and is an error.
 */
export function pipelineTables(): PipelineTables {
  if (cachedTables) return cachedTables;
  const grammar = cGrammar();
  const lalr = drain(
    lalrSteps(grammar, { resolveDanglingElseByShift: true, maxLr1States: 100_000 }),
  );
  const unresolved = lalr.conflicts.filter((c) => c.resolution === null);
  if (unresolved.length > 0) {
    const c = unresolved[0]!;
    throw new Error(
      `C-subset grammar is not LALR(1) apart from dangling else: ${c.kind} conflict in state ${c.state} on '${c.symbol}' (${c.items.join(' vs ')})`,
    );
  }
  cachedTables = {
    grammar,
    lalr,
    resolutions: lalr.conflicts.filter((c) => c.resolution !== null),
  };
  return cachedTables;
}

export interface PipelineParseOutput {
  ast: Ast | null;
  /** The recorded LALR driver trace (shift/reduce/accept/error events; the
   *  reduce events grow the parse tree the AST is folded from). */
  recorded: Recorded<LrParseUiState, LrParseEvent, LrParseResult>;
  diagnostics: Diagnostic[];
}

/** End-of-input fallback span: right after the last token. */
function eofSpan(tokens: TokenStream): SourceSpan {
  const last = tokens.tokens[tokens.tokens.length - 1];
  if (!last) return { start: 0, end: 0, line: 1, col: 1 };
  return {
    start: last.span.end,
    end: last.span.end,
    line: last.span.line,
    col: last.span.col + (last.span.end - last.span.start),
  };
}

/**
 * Parse a token stream with the memoized LALR(1) table. On success returns the
 * Ast (deterministic preorder node ids, spans covering constituent tokens);
 * on a syntax error returns ast = null plus an educational diagnostic carrying
 * the expected-terminal set and the offending token's span.
 */
export function parse(tokens: TokenStream): PipelineParseOutput {
  const { grammar, lalr } = pipelineTables();
  const input: ParseInputSym[] = tokens.tokens
    .filter((t) => t.type !== '$') // the driver appends its own endmarker
    .map((t) => ({ term: t.type, lexeme: t.lexeme, tokenIndex: t.index, span: t.span }));

  const recorded = lrParseRun(grammar, lalr, input, { id: 'syntax.pipeline-parse' });
  const result = recorded.result;

  if (!result.accepted) {
    const err = result.error;
    const offending =
      err && err.tokenIndex !== null ? tokens.tokens[err.tokenIndex] : undefined;
    const span = offending?.span ?? eofSpan(tokens);
    const found =
      err === null ? 'end of input' : err.found === '$' ? 'end of input' : `'${offending?.lexeme ?? err.found}'`;
    const expected = err ? err.expected.join(', ') : '';
    const diagnostics: Diagnostic[] = [
      {
        phase: 'syntax',
        severity: 'error',
        message: `Syntax error: unexpected ${found}; expected one of: ${expected}`,
        rule: `LR parsing (§4.6.3): ACTION[${err?.state ?? '?'}, ${err?.found ?? '$'}] is empty — in this parser configuration no shift or reduce applies`,
        hint: 'The expected-terminal list is exactly the set of non-blank ACTION entries in the current parser state.',
        span,
      },
    ];
    return { ast: null, recorded, diagnostics };
  }

  const rootId = result.roots[result.roots.length - 1];
  if (rootId === undefined) throw new Error('accepted parse produced no tree');
  const ast = buildAst(grammar, result.nodes, rootId, tokens.tokens);
  return { ast, recorded, diagnostics: [] };
}

/** Test hook: reset the memoized tables (not used by the pipeline). */
export function resetPipelineTablesForTest(): void {
  cachedTables = null;
}
